import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FitLog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <header className="sticky top-0 z-100 border-b border-border bg-background/90 backdrop-blur-sm">
          <Navbar />
        </header>
        <main className="min-h-screen p-4 *:container *:mx-auto">
          {children}
        </main>
        <footer className="border-t border-border bg-background">
          <Footer />
        </footer>

      </body>
    </html>
  );
}
